application: naplesbg
version: 2
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /maps/(.*\.svg)
  static_files: maps/\1
  upload: maps/(.*\.svg)
  mime_type: image/svg+xml

- url: /maps/(.*\.png)
  static_files: maps/\1
  upload: maps/(.*\.png)

- url: /maps/(.*\.pdf)
  static_files: maps/\1
  upload: maps/(.*\.pdf)
  mime_type: application/pdf

- url: /.*
  script: main.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

builtins: 
- datastore_admin: on
- remote_api: on
